build:
  stage: build
  needs: []
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA . -f docker/Dockerfile
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
