name: Beeper Docker image

on:
  push:
    branches: ["beeper"]
env:
  CI_REGISTRY_IMAGE: "${{ secrets.CI_REGISTRY }}/sygnal"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          tags: ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
          push: true
