name: Linting and Tests
on:
  push:
    branches: ["main", "beeper"]
  pull_request:

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1
        with:
          install-project: "false"
          python-version: "3.11"

      - run: poetry run tox -e check_codestyle

  check-types-mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1
        with:
          install-project: "false"
          python-version: "3.11"

      - run: poetry run tox -e check_types

  run-unit-tests:
    name: Unit tests
    needs: [check-code-style, check-types-mypy]
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "."
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install -e .
      - run: python -m twisted.trial tests
